backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: main # Branch to update
  repo: marioaks/portfolio # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}.md"
    media_folder: 'assets'
    public_folder: 'assets'
    path: '{{slug}}/index'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Collaborators", name: "collaborators", widget: "list" }
      - { label: "Embedded Images", name: "embeddedImages", widget: "list", field: {label: Image, name: image, widget: image}}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
